version: '{build}'
pull_requests:
  do_not_increment_build_number: true
os: Windows Server 2012 R2
configuration: ReleaseWin
platform:
- x64
- x86
clone_depth: 1
before_build:
- ps: >-
    nuget restore -DisableParallelProcessing

    (Get-Content -Encoding UTF8 'PitchTracker\PitchTracker.vcxproj') | Foreach-Object {$_ -replace 'v110_xp', 'v120_xp'} | Set-Content -Encoding UTF8 'PitchTracker\PitchTracker.vcxproj'
build:
  project: Vocaluxe.sln
  verbosity: normal
after_build:
- cd Output
- 7z a Vocaluxe_%APPVEYOR_REPO_BRANCH%_Windows_%PLATFORM%.zip *
- appveyor PushArtifact Vocaluxe_%APPVEYOR_REPO_BRANCH%_Windows_%PLATFORM%.zip -FileName Vocaluxe_%APPVEYOR_REPO_BRANCH%_Windows_%PLATFORM%.zip -DeploymentName ReleaseZip
- cd ..
test: off
artifacts:
- path: Output\Vocaluxe_{APPVEYOR_REPO_BRANCH}_Windows_{PLATFORM}.zip
  name: ReleaseZip
before_deploy:
- set GIT_VERSION_TAG=git describe --long
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME) ({APPVEYOR_REPO_COMMIT_TIMESTAMP})
  description: 'Version: {GIT_VERSION_TAG}'
  auth_token:
    secure: QBwVoI9PlI+PWfX8vtjH22cSPhj2nwJ78CQcwC4Olsibn1QNar2KX4HEfOGNbazA
  artifact: ReleaseZip
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: true
- provider: GitHub
  tag: Nightly
  release: Current Nightly ({APPVEYOR_REPO_COMMIT_TIMESTAMP})
  description: 'Version: {GIT_VERSION_TAG}'
  auth_token:
    secure: QBwVoI9PlI+PWfX8vtjH22cSPhj2nwJ78CQcwC4Olsibn1QNar2KX4HEfOGNbazA
  artifact: ReleaseZip
  on:
    branch: appveyorTest